runtime: python311
entrypoint: gunicorn kbsb.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
service: kbsb-api

env_variables:
  ACTIVE_ENV: prod
  FILESTORE_BUCKET: website-kbsb-prod.appspot.com
  GOOGLE_PROJECT_ID: website-kbsb-prod
  GOOGLE_CLIENT_ID: "658290412135-v6ah768urdv83dn76ra4mkiovdalal2k.apps.googleusercontent.com"

handlers:
  - url: /.*
    script: auto
    secure: always
